"use client";
import {useEffect,useState} from "react";
type Place={sourceId:string;title:string;address:string;type:string;mapQuery:string};
type Idea={id:string;title:string;category:string;address?:string|null;note?:string|null;mapQuery?:string|null;imageKey?:string|null};
const cities=["Chicago","Dallas","Orlando"];
const covers:Record<string,string>={Chicago:"https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80",Dallas:"https://images.unsplash.com/photo-1531219572328-a0171b4448a3?auto=format&fit=crop&w=900&q=80",Orlando:"https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=900&q=80"};
export default function Home(){const[city,setCity]=useState("Chicago"),[name,setName]=useState(""),[id,setId]=useState(""),[file,setFile]=useState<File|null>(null),[query,setQuery]=useState(""),[places,setPlaces]=useState<Place[]>([]),[ideas,setIdeas]=useState<Idea[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
const load=()=>fetch("/api/suggestions?city="+city).then(r=>r.json()).then(setIdeas);useEffect(load,[city]);
async function enter(){if(!name.trim())return setMsg("Informe seu nome.");setId(crypto.randomUUID());if(file){const f=new FormData();f.append("file",file);await fetch("/api/uploads",{method:"POST",body:f})}setMsg("Você entrou na aventura!")}
async function search(){setBusy(true);setMsg("");const r=await fetch("/api/places/search?q="+encodeURIComponent(query)+"&city="+city);const d=await r.json();setPlaces(Array.isArray(d)?d:[]);if(!Array.isArray(d))setMsg(d.error||"Busca indisponível.");setBusy(false)}
async function add(p:Partial<Place>){if(!id)return setMsg("Entre com seu nome antes de adicionar ideias.");const r=await fetch("/api/suggestions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({participantId:id,city,title:p.title||query,category:p.type||"Ideia",address:p.address||"",mapQuery:p.mapQuery||p.title||query,note:"",source:"manual"})});if(r.ok){setMsg("Ideia adicionada ao grupo!");load()}else setMsg("Não foi possível salvar.");}
return <main><header className="hero" style={{backgroundImage:`linear-gradient(110deg,#123653cc,#12365333),url(${covers[city]})`}}><p>A NOSSA AVENTURA EM FAMÍLIA</p><h1>Chicago, Dallas<br/><em>& Orlando</em></h1><p>Planejem juntos, salvem ideias e criem memórias.</p></header><nav>{cities.map(c=><button className={c===city?"on":""} onClick={()=>setCity(c)} key={c}>{c}</button>)}</nav><section className="city"><h2>Descubra {city}</h2><p>Pesquise restaurantes, passeios e lugares especiais para a família.</p><div className="write"><input aria-label="Buscar lugares" value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Ex.: pizza, museu, parque"} /><button onClick={search} disabled={busy}>{busy?"Buscando…":"Buscar"}</button></div>{places.map(p=><article className="idea" key={p.sourceId}><div><b>{p.title}</b><p>{p.address}</p><small>{p.type}</small></div><a target="_blank" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(p.mapQuery)}>Maps</a><button onClick={()=>add(p)}>Adicionar</button></article>)}</section><section className="city"><h2>Ideias da família</h2><div className="write"><input aria-label="Adicionar ideia manual" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Adicionar uma ideia manualmente"/><button onClick={()=>add({title:query,type:"Ideia"})}>Salvar</button></div>{ideas.map(i=><article className="idea" key={i.id}><div><b>{i.title}</b><p>{i.address}</p><small>{i.category}</small></div>{i.mapQuery&&<a target="_blank" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(i.mapQuery)}>Maps</a>}</article>)}</section><section className="intro"><h2>Entre na viagem</h2><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu primeiro nome"/></label><label>Foto (JPG, PNG ou WebP até 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="join" onClick={enter}>Participar</button>{msg&&<p role="status">{msg}</p>}</section></main>}
