"use client";
import {useEffect,useState} from "react";
import {Camera,MapPin,Search,Upload,X} from "lucide-react";
const cities=["Chicago","Dallas","Orlando"];
const images:Record<string,string>={Chicago:"https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",Dallas:"https://images.unsplash.com/photo-1531219572328-a0171b4448a3?auto=format&fit=crop&w=1200&q=80",Orlando:"https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=1200&q=80"};
export default function Home(){const[city,setCity]=useState("Chicago"),[open,setOpen]=useState(true),[name,setName]=useState(""),[avatar,setAvatar]=useState(""),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[q,setQ]=useState(""),[results,setResults]=useState<any[]>([]),[notice,setNotice]=useState("");
const choose=(f?:File)=>{if(!f)return;if(!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>5*1024*1024)return setNotice("Use JPG, PNG ou WebP de até 5 MB.");setFile(f);setAvatar(URL.createObjectURL(f));setNotice("")};
async function enter(){if(!name.trim())return setNotice("Digite seu nome para entrar.");setBusy(true);if(file){const d=new FormData();d.append("file",file);await fetch("/api/uploads",{method:"POST",body:d})}setBusy(false);setOpen(false)}
async function search(){const r=await fetch("/api/places/search?q="+encodeURIComponent(q)+"&city="+city);setResults(await r.json())}
return <main><header className="hero" style={{backgroundImage:`linear-gradient(110deg,#123653d9,#12365344),url(${images[city]})`}}><p>VIAGEM EM FAMÍLIA • 2026</p><h1>Chicago, Dallas<br/><em>& Orlando</em></h1><p>Ideias, votos e memórias para uma viagem inesquecível.</p></header><nav>{cities.map(c=><button className={city===c?"on":""} key={c} onClick={()=>setCity(c)}>{c}</button>)}<button className="me" onClick={()=>setOpen(true)}>{avatar?<img src={avatar} alt="Seu perfil"/>:<Camera/>}{name||"Seu perfil"}</button></nav><section className="city"><p className="eyebrow"><MapPin/> DESCOBRIR EM {city.toUpperCase()}</p><h2>Encontrem o próximo lugar favorito.</h2><div className="write"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pizza, museu, parque..." aria-label="Buscar lugares"/><button onClick={search}><Search/> Buscar</button></div><div className="grid">{Array.isArray(results)&&results.map(p=><article key={p.sourceId}><div className="body"><h3>{p.title}</h3><p>{p.address}</p><small>{p.type}</small><a target="_blank" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(p.mapQuery)}>Abrir no Maps</a></div></article>)}</div></section>{open&&<div className="profile-backdrop"><section className="profile-card"><button className="x" onClick={()=>setOpen(false)} aria-label="Fechar"><X/></button><div className="profile-avatar">{avatar?<img src={avatar} alt="Prévia da foto"/>:<Camera/>}</div><p className="eyebrow">BEM-VINDO AO ROTEIRO</p><h2>Como a família vai reconhecer você?</h2><p>Seu perfil aparece ao lado das suas ideias, votos e comentários.</p><label>Seu primeiro nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Juliana" autoFocus/></label><label className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/><Upload/><span>{file?file.name:"Escolher ou arrastar uma foto"}</span><small>JPG, PNG ou WebP · até 5 MB</small></label>{notice&&<p role="alert" className="notice">{notice}</p>}<button className="join" disabled={busy} onClick={enter}>{busy?"Preparando seu perfil…":"Entrar no roteiro"}</button></section></div>}</main>}
